include "../types.fbs";

namespace fbs;

attribute "optional";
attribute "algorithm_specific_options";

table GreedyOptions {}

table ExtremePointOptions {}

table ShitStackOptions {}

table PHPSolverOptions {
  balance_weight: bool = null;
  all_permutations: bool = null;
  single_box: bool = null;
  strict_item_order: bool = null;
  best_subset: bool = null;
  max_boxes: uint = null;
  allow_rotation: bool = true;
}

union SolveStrategyOptions {
  GreedyOptions,
  ExtremePointOptions,
  ShitStackOptions,
  PHPSolverOptions,
}

enum SolveAlgorithm : byte {
	Greedy = 0,
	ExtremePoint = 1,
	ShitStack = 2,
  PHPSolver = 3,
}

table SolveRequest {
  boxes: [BoxType] (required);
  items: [ItemType] (required);
  algorithm: SolveAlgorithm = ExtremePoint;
  options: SolveOptions (optional);
}

table SolveOptions {
  timeout_ms: uint = null;
  algo_options: SolveStrategyOptions (algorithm_specific_options);
}

table ItemPlacement {
  item_code: string;
  item_reference: string;
  x: uint;
  y: uint;
  z: uint;
  width: uint;
  length: uint;
  depth: uint;
}

table BoxResult {
  box_reference: string;
  width: uint;
  length: uint;
  depth: uint;
  placements: [ItemPlacement];
  total_weight: float = null;
  utilization: float = null;
  outer_width: uint = null;
  outer_length: uint = null;
  outer_depth: uint = null;
}

table SolveResponse {
  results: [BoxResult];
  failed: [ItemType];
  algorithm_us: uint = 0;
  server_us: uint = 0;
}

root_type SolveRequest;
