namespace fbs;

attribute "optional";

enum RotationPolicy : byte {
  Never = 0,
  KeepFlat = 1,
  BestFit = 2
}

table PlacementConstraint {
  no_stacking: bool = null;
  required_vertical: bool = null;
  min_x: uint = null;
  min_y: uint = null;
  min_z: uint = null;
  max_x: uint = null;
  max_y: uint = null;
  max_z: uint = null;
}

table BoxType {
  reference: string;
  width: uint;
  length: uint;
  depth: uint;

  max_weight: float = null;
  box_weight: float = null;
  active: bool = null;
  maximum_boxes: uint = null;
}

table ItemType {
  item_code: string;
  item_reference: string;
  width: uint;
  length: uint;
  depth: uint;
  weight: float;
  quantity: uint = null;

  box_group: string (optional);
  rotation_policy: RotationPolicy = null;
  linked_group: string (optional);
  constraint: PlacementConstraint (optional);
}
