import fs from "node:fs";
import path from "node:path";
import { repoRoot } from "../../shared.mjs";
import {
	integerFields,
	resolveField,
	resolveTable,
} from "../schema/analyze.mjs";
import { INT_RANGES } from "../schema/ir.mjs";

export const CPP_OUT = path.join(repoRoot, 'src', 'gen')

const DOMAIN_SCALAR_TYPES = {
	double: "double",
	float: "float",
	bool: "bool",
	byte: "int8_t",
	ubyte: "uint8_t",
	short: "int16_t",
	ushort: "uint16_t",
	int: "int32_t",
	uint: "uint32_t",
	long: "int64_t",
	ulong: "uint64_t",
};

const DOMAIN_DEFAULTS = {
	double: "0.0",
	float: "0.0f",
	bool: "false",
	byte: "0",
	ubyte: "0",
	short: "0",
	ushort: "0",
	int: "0",
	uint: "0",
	long: "0",
	ulong: "0",
};

function cppRangeCheck(requestName, field) {
	const r = INT_RANGES[field.scalar];
	const cppType = DOMAIN_SCALAR_TYPES[field.scalar];
	return [
		`\t${cppType} const ${field.name} = out.${field.name};`,
		`\tif (${field.name} < ${r.cppMin} || ${field.name} > ${r.cppMax}) {`,
		`\t\terror = "${requestName} ${field.name} out of ${r.label} range";`,
		"\t\treturn false;",
		"\t}",
	].join("\n");
}

function cppRangeChecks(requestName, fields) {
	const blocks = integerFields(fields).map((f) =>
		cppRangeCheck(requestName, f),
	);
	return blocks.length > 0 ? `${blocks.join("\n\n")}\n` : "";
}

export function generateCpp(schema, basename, label) {
	const { namespace, request, response, tables, unions } = schema;
	const requestFields = resolveTable(request, tables, unions);
	const checksText = cppRangeChecks(request, requestFields);

	return `// Generated by node/scripts/generate.mjs from ${label}. DO NOT EDIT.

#pragma once

#include "${basename}_generated.h"

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>

namespace ${namespace} {
namespace translation {

inline bool decodeRequest(uint8_t const* data, std::size_t size, ${request}T& out, std::string& error)
{
\tflatbuffers::Verifier verifier(data, size);
\tif (!${namespace}::Verify${request}Buffer(verifier)) {
\t\terror = "Malformed ${request} buffer";
\t\treturn false;
\t}
\t${namespace}::Get${request}(data)->UnPackTo(&out);

${checksText}\treturn true;
}

inline std::vector<uint8_t> encodeResponse(${response}T const& response)
{
\tflatbuffers::FlatBufferBuilder builder;
\tbuilder.Finish(${namespace}::${response}::Pack(builder, &response));
\treturn std::vector<uint8_t>(builder.GetBufferPointer(), builder.GetBufferPointer() + builder.GetSize());
}

} // namespace translation
} // namespace ${namespace}
`;
}

function domainType(field) {
	const optionalize = (type) =>
		field.nullable ? `std::optional<${type}>` : type;
	switch (field.kind) {
		case "scalar":
			return optionalize(field.enumName ?? DOMAIN_SCALAR_TYPES[field.scalar]);
		case "string":
			return optionalize("std::string");
		case "vector-scalar":
			return `std::vector<${DOMAIN_SCALAR_TYPES[field.scalar]}>`;
		case "vector-string":
			return "std::vector<std::string>";
		case "table":
			return optionalize(field.table);
		case "vector-table":
			return `std::vector<${field.table}>`;
	}
}

function domainDefault(field) {
	if (field.nullable) return "std::nullopt";
	if (field.defaultValue) {
		if (field.defaultValue === "true" || field.defaultValue === "false")
			return field.defaultValue;
		if (field.enumName) return `${field.enumName}::${field.defaultValue}`;
		return field.defaultValue;
	}
	switch (field.kind) {
		case "scalar":
			return DOMAIN_DEFAULTS[field.scalar];
		default:
			return "{}";
	}
}

function domainStruct(name, fields) {
	const members = fields
		.map((f) => {
			const value = domainDefault(f);
			return value === "{}"
				? `\t${domainType(f)} ${f.name}{};`
				: `\t${domainType(f)} ${f.name} = ${value};`;
		})
		.join("\n");
	return `struct ${name} {\n${members}\n};`;
}

// Domain structs hold nested tables by value, so dependencies must be defined
// before the tables that reference them.
function domainOrder(tables, unions, names = Object.keys(tables)) {
	const ordered = [];
	const visited = new Set();
	const visit = (name) => {
		if (visited.has(name)) return;
		visited.add(name);
		for (const raw of tables[name]) {
			const f = resolveField(raw, tables, unions);
			if (
				(f.kind === "table" || f.kind === "vector-table") &&
				tables[f.table]
			) {
				visit(f.table);
			}
		}
		ordered.push(name);
	};
	for (const name of names) visit(name);
	return ordered.filter((name) => names.includes(name));
}

function cppFieldToDomain(field) {
	const access = `value.${field.name}`;
	const out = `out.${field.name}`;
	if (field.unionMember) {
		const unionField = field.unionField;
		const enumPrefix = field.unionTypeName;
		return [
			`\tif (value.${unionField}.type == ::fbs::${enumPrefix}_${field.unionMember}) {`,
			`\t\t${out} = toDomain(*value.${unionField}.As${field.unionMember}());`,
			"\t}",
		].join("\n");
	}
	switch (field.kind) {
		case "scalar":
			if (field.nullable) {
				return `\tif (${access}.has_value()) {\n\t\t${out} = ${field.enumName ? `toDomain(*${access})` : `*${access}`};\n\t}`;
			}
			return `\t${out} = ${field.enumName ? `toDomain(${access})` : access};`;
		case "string":
			if (field.nullable) {
				return `\tif (!${access}.empty()) {\n\t\t${out} = ${access};\n\t}`;
			}
			return `\t${out} = ${access};`;
		case "vector-scalar":
		case "vector-string":
			return `\t${out} = ${access};`;
		case "table":
			return `\tif (${access}) {\n\t\t${out} = toDomain(*${access});\n\t}`;
		case "vector-table":
			return [
				`\t${out}.reserve(${access}.size());`,
				`\tfor (auto const& item : ${access}) {`,
				`\t\t${out}.push_back(toDomain(*item));`,
				"\t}",
			].join("\n");
	}
}

function cppFieldFromDomain(field, namespace) {
	const access = `value.${field.name}`;
	const out = `out.${field.unionField || field.name}`;
	if (field.unionMember) {
		return [
			`\tif (${access}.has_value()) {`,
			`\t\t${out}.Set(fromDomain(*${access}));`,
			"\t}",
		].join("\n");
	}
	switch (field.kind) {
		case "scalar":
			if (field.nullable) {
				return `\tif (${access}.has_value()) {\n\t\t${out} = ${field.enumName ? `fromDomain(*${access})` : `*${access}`};\n\t}`;
			}
			return `\t${out} = ${field.enumName ? `fromDomain(${access})` : access};`;
		case "string":
			if (field.nullable) {
				return `\tif (${access}.has_value()) {\n\t\t${out} = *${access};\n\t}`;
			}
			return `\t${out} = ${access};`;
		case "vector-scalar":
		case "vector-string":
			return `\t${out} = ${access};`;
		case "table":
			if (field.nullable) {
				return `\tif (${access}.has_value()) {\n\t\t${out} = std::make_unique<${namespace}::${field.table}T>(fromDomain(*${access}));\n\t}`;
			}
			return `\t${out} = std::make_unique<${namespace}::${field.table}T>(fromDomain(${access}));`;
		case "vector-table":
			return [
				`\t${out}.reserve(${access}.size());`,
				`\tfor (auto const& item : ${access}) {`,
				`\t\t${out}.push_back(std::make_unique<${namespace}::${field.table}T>(fromDomain(item)));`,
				"\t}",
			].join("\n");
	}
}

function domainConversions(namespace, name, fields) {
	const lines = [];
	lines.push(
		`inline ${name} toDomain([[maybe_unused]] ${namespace}::${name}T const& value)`,
	);
	lines.push("{");
	lines.push(`\t${name} out;`);
	for (const block of fields.map(cppFieldToDomain)) {
		lines.push("", block);
	}
	lines.push("", "\treturn out;");
	lines.push("}");
	lines.push("");
	lines.push(
		`inline ${namespace}::${name}T fromDomain([[maybe_unused]] ${name} const& value)`,
	);
	lines.push("{");
	lines.push(`\t${namespace}::${name}T out;`);
	for (const block of fields.map((f) => cppFieldFromDomain(f, namespace))) {
		lines.push("", block);
	}
	lines.push("", "\treturn out;");
	lines.push("}");
	return lines.join("\n");
}

export function generateDomain(schema, basename, label) {
	const { namespace, tables, unions } = schema;
	const order = domainOrder(tables, unions, schema.declaredTables);
	const enums = (schema.declaredEnums ?? [])
		.map((name) => {
			const enumInfo = schema.enums[name];
			const values = Object.entries(enumInfo.values)
				.map(([value, number]) => `\t${value} = ${number}`)
				.join(",\n");
			return `enum class ${name} : ${DOMAIN_SCALAR_TYPES[enumInfo.underlying]} {\n${values}\n};`;
		})
		.join("\n\n");
	const enumConversions = (schema.declaredEnums ?? [])
		.map((name) => {
			const enumInfo = schema.enums[name];
			const toDomainCases = Object.keys(enumInfo.values)
				.map(
					(value) =>
						`\tcase ::${namespace}::${name}_${value}: return ${name}::${value};`,
				)
				.join("\n");
			const fromDomainCases = Object.keys(enumInfo.values)
				.map(
					(value) =>
						`\tcase ${name}::${value}: return ::${namespace}::${name}_${value};`,
				)
				.join("\n");
			return `inline ${name} toDomain(::${namespace}::${name} value)\n{\n\tswitch (value) {\n${toDomainCases}\n\tdefault: throw std::invalid_argument("invalid ${name} value");\n\t}\n}\n\ninline ::${namespace}::${name} fromDomain(${name} value)\n{\n\tswitch (value) {\n${fromDomainCases}\n\tdefault: throw std::invalid_argument("invalid ${name} value");\n\t}\n}`;
		})
		.join("\n\n");
	const structs = order
		.map((name) => domainStruct(name, resolveTable(name, tables, unions)))
		.join("\n\n");
	const conversions = order
		.map((name) =>
			domainConversions(namespace, name, resolveTable(name, tables, unions)),
		)
		.join("\n\n");
	const includedDomains = (schema.includes ?? [])
		.map(
			(include) =>
				`#include "${path.basename(include, ".fbs")}_domain_generated.h"`,
		)
		.join("\n");
	const generatedIncludes = [
		`#include "${basename}_generated.h"`,
		includedDomains,
	]
		.filter(Boolean)
		.join("\n");

	return `// Generated by node/scripts/generate.mjs from ${label}. DO NOT EDIT.

#pragma once

${generatedIncludes}

#include <cstdint>
#include <memory>
#include <optional>
#include <stdexcept>
#include <string>
#include <vector>

namespace ${namespace} {
namespace domain {

${enums}

${enumConversions}

${structs}

${conversions}

} // namespace domain
} // namespace ${namespace}
`;
}

export const cppTarget = {
	id: "cpp",
	flatcArgs: ["--cpp", "--gen-object-api"],
	outputDir: CPP_OUT,
	emit(schema, { basename, label }) {
		const domain = path.join(CPP_OUT, `${basename}_domain_generated.h`);
		fs.writeFileSync(domain, generateDomain(schema, basename, label));
		const paths = [domain];
		if (schema.request) {
			const translation = path.join(
				CPP_OUT,
				`${basename}_translation_generated.h`,
			);
			fs.writeFileSync(translation, generateCpp(schema, basename, label));
			paths.push(translation);
		}
		return paths;
	},
};
